name: text-to-socket-engine
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        arch: [x86, amd64]
    steps:
      - uses: actions/checkout@v2
      - run: |
          @echo on
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
          call build.cmd
        shell: cmd
        working-directory: .\text-to-socket-engine
      - run: 7z a text-to-socket-engine.zip register.cmd unregister.cmd TextToSocketEngine.dll
        working-directory: .\text-to-socket-engine
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: text-to-socket-engine-${{ matrix.arch }}.zip
          path: text-to-socket-engine/text-to-socket-engine.zip
