name: update

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - run: npm i -g pnpm
      - run: pnpm update -r --latest -E
      - run: |
          ( cd ./components/assistive-webdriver && pnpm install p-queue@6.6.2 )
          ( cd ./components/assistive-webdriver && pnpm install node-fetch@2.6.7 )
          ( cd ./components/assistive-webdriver && pnpm install -D @types/node-fetch@2.6.1 )
          ( cd ./components/assistive-playwright-client && pnpm install node-fetch@2.6.7 )
          ( cd ./components/assistive-playwright-client && pnpm install -D @types/node-fetch@2.6.1 )
          ( cd ./components/assistive-playwright-server && pnpm install -D node-fetch@2.6.7 )
          ( cd ./components/assistive-playwright-server && pnpm install -D @types/node-fetch@2.6.1 )
          ( cd ./components/assistive-playwright-tester && pnpm install node-fetch@2.6.7 )
          ( cd ./components/assistive-playwright-tester && pnpm install -D @types/node-fetch@2.6.1 )
      - name: Create pull request
        uses: peter-evans/create-pull-request@bd72e1b7922d417764d27d30768117ad7da78a0e # v4.0.2
        with:
          commit-message: Update all dependencies
          branch: dependencies
          title: Update all dependencies
          body: Update all dependencies
